### PR TITLE
Manually outtake based on driver throttle

### PR DESCRIPTION
**Pull request by calebeby**

### CODE REVIEW

**Comment by simonflyer11** [comment]
is that just for me? like with my binary trigger?

**Comment by calebeby** [comment]
No now outtake is on Ben's throttle so he can do it slower or faster or however he wants

https://github.com/Pigmice2733/frc-2018/pull/23/files#diff-e85481ababc1c141ef8d3430eee259c2R74

**Comment by simonflyer11** [comment]
oh ok cool

**Review by simonflyer11 — COMMENTED** [review]
i am groot

**Review by brendanburkhart — APPROVED** [review]

**Pull request merged**
