### PR TITLE
Add switch arm

### PR DESCRIPTION
**Pull request by GreenBeard**
The commits should be completely correct now.

### CODE REVIEW

**Review by calebeby — APPROVED** [review]

**Comment by calebeby** [comment]
Thanks for doing this, Alex!

Also good job getting git to work right!

**Comment by GreenBeard** [comment]
@calebeby Well it appears that only squash and merge is allowed for this repo. We should probably allow other options :cry: . If you really want I can squash the two together.

**Comment by calebeby** [comment]
I intentionally disabled the other options. Is there a reason that you want the other options?

**Comment by GreenBeard** [comment]
Well @AccordingtoProphecy authored the first, while I authored the second one. It seems appropriate therefore to have two separate patches :man_shrugging:

**Comment by calebeby** [comment]
Hm, I agree that normal merge would be good here. I wish that you could change the default without disabling the others. I'm going to allow rebase merging (adds commits to master w/o merge commit) so that squash and merge is still the default

**Comment by calebeby** [comment]
Thanks, good job 🎉

**Pull request merged**
